#ifndef REPHELPERQT_GLOBAL_H
#define REPHELPERQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPHELPERQT_LIBRARY)
#  define REPHELPERQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPHELPERQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPHELPERQT_GLOBAL_H
